version: "3"
services:

  client:
    build:
      context: ./client/building_systems
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - mern-network
    volumes:
      - ./client/building_systems/src:/usr/app/src
      - ./client/building_systems/public:/usr/app/public
    depends_on:
      - server
    environment:
      - REACT_APP_SERVER=http://localhost:8082
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    stdin_open: true
    tty: true
  
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    networks:
      - mern-network
    volumes:
      - ./server/src:/usr/app/src
    depends_on:
      - db
    environment:
      - MONGO_URL=mongodb://db:27017
      - CLIENT=http://localhost:3000
    command: /usr/app/node_modules/.bin/nodemon -L src/index.js

  db:
    image: mongo:3.6.19-xenial
    environment:
      MONGO_INITDB_ROOT_USERNAME: FederalTroll1
      MONGO_INITDB_ROOT_PASSWORD: IndicatePassedStop31102000
      MONGO_INITDB_DATABASE: myFirstDatabase
    ports:
      - 27017:27019
    networks:
      - mern-network
    volumes:
      - mongo-data:/data/db

networks:
  mern-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
